#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Little Rock .NET User Group

# Short bio or description (displayed in the header)
description:

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://lrdnug.github.io/images/lrdnug_logo_whitebg_200x81.png

officers:
  president: Chris Steven
  vice-president: open position
  webmaster: Michael Collins
  sponsor-coord: Abby Sims
  training-coord: open position
  event-coord: open position

officer-emails:
  president: president@lrdnug.org
  #vice-president: vicepresident@lrdnug.org
  vice-president: president@lrdnug.org
  webmaster: webmaster@lrdnug.org
  sponsor-coord: sponsors@lrdnug.org
  #training-coord: training@lrdnug.org
  training-coord: president@lrdnug.org
  #event-coord: events@lrdnug.org
  event-coord: president@lrdnug.org


sponsors:
  - name: "GDH Consulting"
    image: "/images/logos/gdh-logo.jpg"
    url: "http://www.gdhconsulting.com"
    description: "GDH Consulting is a specialized consulting and resource firm focused on providing qualified professionals within the Information Technology, Finance &amp; Accounting, and Consulting industries to commercial and government sectors. GDH Consulting was the first sponsor of the Little Rock .Net Users Group and has been a constant source of support for our group."
    level: "gold" 
  - name: "Inuvo"
    image: "/images/logos/inuvo_logo.png" 
    url: "http://www.inuvo.com/" 
    description: "Inuvo is an internet marketing and technology company that delivers purchase-ready customers to advertisers through a broad network of desktop and mobile websites and apps."
    level: "silver"
  - name: "JetBrains"
    image: "/images/logos/logo_jetbrains.png" 
    url: "http://www.jetbrains.com" 
    description: "At JetBrains, we have a passion for making people more productive through smart software solutions that help them focus more on what they really want to accomplish, and less on mundane, repetitive &quot;computer busy work&quot;."
    level: "partner"
  - name: "Pluralsight"
    image: "/images/logos/PS_logo_F-02.png" 
    url: "http://www.pluralsight.com/" 
    description: "Pluralsight provides high-quality training solutions for Microsoft .NET developers that can fit any schedule or budget. The revolutionary Pluralsight On-Demand! training library provides developers with instant access to a rich collection of online training courses delivered by industry authorities. See what you can learn at pluralsight.com and join the @pluralsight community on Twitter."
    level: "partner"
  - name: "Telerik"
    image: "/images/logos/telerik_new-logo.png" 
    url: "http://www.telerik.com" 
    description: "Telerik’s mission is to make software development easier and more enjoyable. Our tools for agile project management, collaboration, development and testing allow companies of all sizes to create richer, more stable and aesthetic software faster than ever before. Trusted by over 100,000 customers worldwide for our devotion to quality and customer care, Telerik helps technical and business professionals maximize their productivity and &quot;deliver more than expected” every day."
    level: "partner"
  - name: "O'Reilly"
    image: "http://cdn.oreillystatic.com/community/promote/ug_ad_200_superowl.gif" 
    url: "http://www.oreilly.com"
    description: "O'Reilly Media spreads the knowledge of innovators through its books, online services, magazines, research, and conferences. Since 1978, O'Reilly has been a chronicler and catalyst of leading-edge development, homing in on the technology trends that really matter and galvanizing their adoption by amplifying &quotfaint signals&quot from the alpha geeks who are creating the future. An active participant in the technology community, the company has a long history of advocacy, meme-making, and evangelism."
    level: "partner"
  - name: "SqlSmash"
    image: "/images/logos/sqlsmash_small.png" 
    url: "http://sqlsmash.com/" 
    description: "SqlSmash is a plugin for Sql Server Management Studio (SSMS) 2012 that helps you in writing maintainable SQL scripts, understanding code faster and navigating around easily."
    level: "partner"
  - name: "Devart"
    image: "/images/logos/devart.png" 
    url: "https://www.devart.com/" 
    description: "Devart is one of the leading developers of database tools and administration software, ALM solutions, data providers for various database servers, data integration and backup solutions. The company also implements Web and Mobile development projects."
    level: "partner"
# valid display-locations are:
#   innovationhub
#   few
#
display-location: innovationhub
#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook: lrdnug
  flickr:
  github: lrdnug
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: lrdnug
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Your disqus shortname, entering this will enable commenting on posts
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-58212966-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://lrdnug.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge
permalink: /:title/
future: true

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
