#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Little Rock .NET User Group

# Short bio or description (displayed in the header)
description:

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://lrdnug.github.io/images/lrdnug_logo_whitebg_200x81.png

officers:
  president: Abby Sims
  vice-president: Vacant
  webmaster: Jeffrey Miller
  sponsor-coord: Travis Jones
  training-coord: Scott Ferguson
  event-coord: Andrew Norwood
officer-emails:
  president: president@lrdnug.org
  vice-president: vicepresident@lrdnug.org
  #vice-president: president@lrdnug.org
  webmaster: webmaster@lrdnug.org
  sponsor-coord: sponsors@lrdnug.org
  training-coord: training@lrdnug.org
  #training-coord: president@lrdnug.org
  event-coord: events@lrdnug.org
  #event-coord: president@lrdnug.org


sponsors:
  - name: "GDH Consulting"
    image: "/images/logos/gdh-logo.jpg"
    url: "http://www.gdhconsulting.com"
    description: "GDH Consulting is a specialized consulting and resource firm focused on providing qualified professionals within the Information Technology, Finance &amp; Accounting, and Consulting industries to commercial and government sectors. GDH Consulting was the first sponsor of the Little Rock .Net Users Group and has been a constant source of support for our group."
    level: "gold"
  # - name: "Inuvo"
  #   image: "/images/logos/inuvo_logo.png"
  #   url: "http://www.inuvo.com/"
  #   description: "Inuvo is an internet marketing and technology company that delivers purchase-ready customers to advertisers through a broad network of desktop and mobile websites and apps."
  #   level: "silver"
  # - name: "Lindsey Software"
  #  image: "/images/logos/lindsey-software-logo.png"
  #  url: "http://www.lindseysoftware.com"
  #  description: "Since 1959, Lindsey has been dedicated to innovation and market leadership in property management solutions designed to make life easier and ease the workload for public housing managers. Our full suite of products and cloud-based solutions has benefits that are easily recognizable by both property managers and tenants of properties utilizing Lindsey Software."
  #  level: "silver"
  - name: "Laravel"
    image: "/images/logos/laravel.png"
    url: "https://www.laravel.com/"
    description: "Laravel is a web application framework with expressive, elegant syntax. Laravel believes development must be an enjoyable, creative experience to be truly fulfilling. Laravel attempts to take the pain out of development by easing common tasks used in the majority of web projects. Laravel is accessible, yet powerful, providing tools needed for large, robust applications. "
    level: "silver"
  - name: "TEKsystems"
    image: "/images/logos/teksystems.jpg"
    url: "https://www.teksystems.com/"
    description: "With nearly 30 years of IT consulting experience, we have the relationships, resources and expertise to help advance your career. We are consistently able to provide you with the best IT job opportunities on a contract, contract-to-hire or direct placement basis through our Consultant Placement ProcessSM ."
    level: "bronze"
  - name: "Arkansas Innovation Hub"
    image: "/images/logos/arhub.png"
    url: "http://arhub.org/"
    description: "The Innovation Hub is a collaborative and diverse community of all ages, interests, and skill levels.  We have worked hard to create an accessible space that is open to anyone who wants to Learn and Build with us."
    level: "partner"
  - name: "JetBrains"
    image: "/images/logos/logo_jetbrains.png"
    url: "http://www.jetbrains.com"
    description: "At JetBrains, we have a passion for making people more productive through smart software solutions that help them focus more on what they really want to accomplish, and less on mundane, repetitive &quot;computer busy work&quot;."
    level: "partner"
  - name: "Pluralsight"
    image: "/images/logos/PS_logo_F-02.png"
    url: "http://www.pluralsight.com/"
    description: "Pluralsight provides high-quality training solutions for Microsoft .NET developers that can fit any schedule or budget. The revolutionary Pluralsight On-Demand! training library provides developers with instant access to a rich collection of online training courses delivered by industry authorities. See what you can learn at pluralsight.com and join the @pluralsight community on Twitter."
    level: "partner"
  - name: "Telerik"
    image: "/images/logos/telerik_new-logo.png"
    url: "http://www.telerik.com"
    description: "Telerik’s mission is to make software development easier and more enjoyable. Our tools for agile project management, collaboration, development and testing allow companies of all sizes to create richer, more stable and aesthetic software faster than ever before. Trusted by over 100,000 customers worldwide for our devotion to quality and customer care, Telerik helps technical and business professionals maximize their productivity and &quot;deliver more than expected” every day."
    level: "partner"
  # - name: "SqlSmash"
  #   image: "/images/logos/sqlsmash_small.png"
  #   url: "http://sqlsmash.com/"
  #   description: "SqlSmash is a plugin for Sql Server Management Studio (SSMS) 2012 that helps you in writing maintainable SQL scripts, understanding code faster and navigating around easily."
  #   level: "partner"
  # - name: "Devart"
  #   image: "/images/logos/devart.png"
  #   url: "https://www.devart.com/"
  #   description: "Devart is one of the leading developers of database tools and administration software, ALM solutions, data providers for various database servers, data integration and backup solutions. The company also implements Web and Mobile development projects."
  #   level: "partner"
  - name: "PostSharp"
    image: "/images/logos/PostSharp.png"
    url: "http://www.postsharp.net/"
    description: "PostSharp is the #1 pattern-aware extension to C# and VB. It allows developers to eradicate boilerplate by offloading repeating work from humans to machines. Includes some the most common patterns and gives you the tools to build your own."
    level: "partner"
  - name: "Redgate"
    image: "/images/logos/rg-logo.png"
    description: "Redgate is the leading Microsoft SQL Server tools vendor and the creator of the SQL Toolbelt."
    url: "https://www.red-gate.com"
    level: "partner"
    name: "packt"
    image: "/images/packt.jpg"
    description: "Packt's mission is to help the world put software to work in new ways."
    url: "https://www.packtpub.com/"
    level: "partner"
    
# valid display-locations are:
#   innovationhub
#   few
#
display-location: innovationhub
#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook: lrdnug
  flickr:
  github: lrdnug
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: lrdnug
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Your disqus shortname, entering this will enable commenting on posts
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-58212966-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://lrdnug.github.io

# If you're hosting your site at a Project repository opartnern GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge
permalink: /:title/
future: true

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
