- title: Microsoft Tech Summit Washington, D.C.
  desc: "Build your enterprise or government cloud and infrastructure skills with a two-day free technical training event"
  startDate: 2017-3-6
  endDate: 2017-3-7
  tags: [in-person, conference, free]
  when: "March 6-7, 2017"
  where: "Washington DC"
  link: "https://www.microsoft.com/en-us/techsummit/washington-dc.aspx"
- title: Project Management Workshop
  desc: |
    Master the art of project planning, and organize your project without omissions, mistakes, or miscalculations.
    Use better communications techniques to get the cooperation, support, and resources that are vital to the project's success.
    Root out waste in every stage of the project — wasted time, money, and effort that endanger a project's success.
    Identify and use indispensable planning and scheduling tools that assure the project is implemented exactly as planned.
    Estimate time and costs with pinpoint accuracy, using a simple 3-point approach that reduces the risk of costly delays and errors.
  startDate: 2017-3-10
  endDate: 2017-3-10
  link: http://www.pryor.com/mkt_info/seminars/desc/PM.asp?zip=72223
  where: Little Rock
  tags: [local, in-person, conference]
- title: Visual Studio Live! 2017
  desc: Fabulous Las Vegas, where developers, software architects, engineers, designers and more will convene for five days of unbiased and cutting-edge education on the Microsoft Platform.
  startDate: 2017-3-13
  endDate: 2017-3-17
  link: https://vslive.com/events/las-vegas-2017/home.aspx
  tags: [in-person, conference]
  where: Las Vegas
  registerInfo: "Save $300 thru 2/17"
- title: "AWS ONLINE TALKS: Uninterrupted Business"
  desc: |
    Cloud security at AWS is the highest priority. As an AWS customer, you will benefit from a data center and network architecture built to meet the requirements of the most security-sensitive organisations.
    An advantage of the AWS cloud is that it allows customers to scale and innovate, while maintaining a secure environment. Customers pay only for the services they use, meaning that you can have the security you need, but without the upfront expenses, and at a lower cost than in an on-premises environment.

    Register to attend our weekly online talks to explore cloud security and compliance topics and get your questions answered during live Q&A.
  startDate: 2017-4-12
  endDate: 2017-6-6
  link: https://aws.amazon.com/events/security-webinars/
  tags: [online, webinar, free]
- title: DockerCon Austin 2017
  desc: DockerCon is the community and container industry conference for makers and operators of next generation distributed apps built with containers. The three-day conference provides talks by practitioners, hands-on labs, an expo hall of Docker ecosystem innovators and great opportunities to share your experiences with other virtual container enthusiasts.
  startDate: 2017-4-17
  endDate: 2017-4-20
  link: http://2017.dockercon.com/
  tags: [in-person, conference]
- title: Microsoft Build 2017
  desc: Software continues to transform the world in remarkable ways and developers are at the center of it. At Microsoft Build 2017 we invite you to join us in downtown Seattle to learn about latest new technologies and exciting plans on the horizon.
  startDate: 2017-5-10
  endDate: 2017-5-12
  link: https://build.microsoft.com/
  where: Seattle, WA
  tags: [in-person, conference]
  registerInfo: "Tickets available 2/14"
- title: Google IO 2017
  startDate: 2017-5-17
  endDate: 2017-5-19
  link: https://events.google.com/io/
  where: Shoreline Amphitheatre, Mountain View, CA
  tags: [in-person, conference]
  registerInfo: "Ticket Application Window: February 22, 10AM PST - February 27, 5PM PST"
- title: PHP[TEK] 2017
  desc: ...the premier PHP conference and annual homecoming for the PHP Community
  startDate: 2017-5-24
  endDate: 2017-5-26
  link: https://tek.phparch.com/
  where: Atlanta
  tags: [in-person, conference]
  registerInfo: Early Bird Ticket sale runs through February 18th, 2017
- title: Music City Code 2017
  desc: Music City Code conference strives to inspire progress in the technology community through education, professional development & thought leadership.
  startDate: 2017-6-1
  endDate: 2017-6-3
  link: https://www.musiccitycode.com/
  where: Nashville
  tags: [in-person, conference]
- title: Arduino workshop
  desc: Arduino? What is that?! Learn the basics of this fun open-source electronic platform. Come explore with us!
  startDate: 2017-6-24
  endDate: 2017-6-24
  link: https://campscui.active.com/orgs/ARHub#/selectSessions/1923602
  where: The Arkansas Regional Innovation Hub
  tags: [in-person, training]
- title: Microsoft Inspire 2017 (Partner conference)
  desc: Microsoft Inspire is where the world meets to transform business. Hear the latest revelations from industry experts, top Microsoft leaders, and fellow Microsoft partners and take part in the face-to-face conversations that can lead to your company’s next big opportunity.
  startDate: 2017-7-9
  endDate: 2017-7-13
  link: https://partner.microsoft.com/en-US/inspire/
  where: DC
  tags: [in-person, conference]
- title: CoderCruise
  desc: For 7 days and 6 nights, you will be on a ship with other attendees, learning from each other, team building and forming community relationships that will last for years to come.  A conference on a cruise is the ultimate immersive experience. The conference will take place on the 3 days at sea.  The remaining 3 days the ship will be at various ports where you will be free to explore the area or join us for a group excursion.
  startDate: 2017-7-16
  endDate: 2017-7-23
  link: https://www.codercruise.com/
  where: Sail from New Orleans
  tags: [in-person, conference]
- title: Tulsa TechFest 2017/Tulsa School of Dev 2017
  desc: Two days of learning and sessions
  startDate: 2017-7-20
  endDate: 2017-7-21
  link: https://twitter.com/TulsaTechFest
  where: Tulsa, OK
  tags: [in-person, conference]
- title: AWS Summit - Chicago
  desc: |
    The AWS Summit brings together the cloud computing community to connect, collaborate and learn about AWS.

    Whether you are new to the cloud or an experienced user, you will learn something new at the AWS Summit. This free event is designed to educate you about the AWS platform. Develop the skills to design, deploy, and operate infrastructure and applications.
  startDate: 2017-7-26
  endDate: 2017-7-27
  link: https://aws.amazon.com/summits/chicago/?refid=ep
  tags: [in-person, conference, free]
- title: Rasberry Pi workshop
  desc: Learn how to set up a Raspberry Pi! This class is perfect for beginners- especially those that own a pi and do not know how to use it!
  startDate: 2017-7-29
  endDate: 2017-7-29
  link: https://campscui.active.com/orgs/ARHub#/selectSessions/1923602
  where: The Arkansas Regional Innovation Hub
  tags: [in-person, training]
- title: KCDC 2017
  desc: |
    The Kansas City Developer Conference is a two-day, multi-track event covering all aspects of software development, design, and project management. We welcome speakers from all over the world who are industry experts that deliver breakout sessions and hands-on workshops to further our attendees’ knowledge and professional skills.
  startDate: 2017-8-3
  endDate: 2017-8-4
  link: http://www.kcdc.info/
  where: Kansas City, MO
  tags: [in-person, conference]
- title: VMworld 2017
  desc: |
    VMworld is VMware’s premier thought leadership and education destination for cloud infrastructure and digital workspace technology professionals. Join us for five days of innovation and learn new skills, hear expert insights and gain the tools to enable business success.
  
    At VMworld, you’ll join the industry’s top thought leaders, subject matter experts and IT professionals to immerse yourself in the latest in cloud infrastructure and business mobility technology. 
  
    This is the one indispensable event to discover the technology, trends and people who are shaping the future of digital business.
  startDate: 2017-8-27
  endDate: 2017-8-31
  link: https://www.vmworld.com/en/us/index.html
  where: Las Vegas
  tags: [in-person, conference]
- title: .Net Conf
  desc: |
    .NET Conf is a free, 3 day virtual developer event co-organized by the .NET community and Microsoft. Over the course of the three days developers have a wide selection of live sessions that feature speakers from the community and .NET product teams. These are the experts in their field and it is a chance to learn, ask questions live, and get inspired for their next software project.
    
    Developers will learn to build for web, mobile, desktop, games, services, libraries and more for a variety of platforms and devices all with .NET. We’ll have presentations on .NET Core and ASP.NET Core, C#, F#, Roslyn, Visual Studio, Xamarin, and much more.
  startDate: 2017-9-19
  endDate: 2017-9-21
  link: http://www.dotnetconf.net/
  tags: [virtual, conference, free]
- title: Strange Loop
  desc: |
    Strange Loop is a multi-disciplinary conference that brings together the developers and thinkers building tomorrow's technology in fields such as emerging languages, alternative databases, concurrency, distributed systems, security, and the web.
  startDate: 2017-9-28
  endDate: 2017-9-30
  link: https://thestrangeloop.com/
  where: St Louis, MO
  tags: [in-person, conference]
- title: Hacktoberfest 2017
  desc: |
    Support open source and earn a limited edition T-shirt.
    Hacktoberfest is a month-long celebration of open source software in partnership with Github.
  startDate: 2017-10-01
  endDate: 2017-10-31
  link: https://hacktoberfest.digitalocean.com/
  tags: [online, hackathon]
- title: Little Rock Tech Fest
  desc: |
    Little Rock Tech Fest is an annual developer conference featuring popular web, mobile, database, devops and related developer topics from industry leaders. It is the event in Little Rock for both professional and aspiring software developers. Speakers from across the country come to present. Students and professionals from across Arkansas and surrounding regions come to learn and network with peers.
    
    Our purpose is to encourage local professionals to increase their skills and to promote the Little Rock region to both experienced and aspiring developers and students.
    
    This is our fifth year hosting the event. Will you join us?
  startDate: 2017-10-05
  endDate: 2017-10-06
  link: http://www.lrtechfest.com/
  where: Little Rock, AR
  tags: [in-person, conference]  
- title: 2017 Northwest Arkansas Technology Summit
  desc: |
    Northwest Arkansas Premier Technology and Innovation Summit. The NWA Technology Summit brings cutting-edge innovation to the latest thinking at the intersection of business and technology.  Want to explore how to innovate and use technology to succeed in the digital era?  Then the Summit is for you. Forward-thinking and practitioner-driven general session speakers and high value breakout sessions will deliver ways that you can effectively collaborate on innovative solutions to common business challenges and learn how technology is powering change and leveling the playing field. 
  startDate: 2017-10-17
  endDate: 2017-10-17
  link: http://www.nwatechsummit.com/
  where: Bentonville, AR
  tags: [in-person, conference]
  twitter: '@NWATech'
- title: Dev Up
  desc: |
    ST. LOUIS DEVELOPER CONFERENCE
    A THREE DAY EVENT FILLED WITH
    KNOWLEDGE & NETWORKING OPPORTUNITIES
  startDate: 2017-10-16
  endDate: 2017-10-18
  link: http://devupconf.org/
  twitter: '@devupconf'
  where: St Louis, MO
  tags: [in-person, conference]  
- title: IT/Dev Connections 2017
  desc: Professional and uniquely personal, enjoy 3 days of deep-dive technical education!
  startDate: 2017-10-23
  endDate: 2017-10-26
  link: http://devconnections.com/dc17/Public/Enter.aspx
  where: San Francisco
  tags: [in-person, conference]
- title: DEVIntersection Fall 2017
  desc: |
    In today’s fast-paced world with technology changing rapidly, it’s a challenge to stay on top of everything new while mastering the fundamentals. This exciting event, now in it’s forth year, brings your favorite Microsoft leaders, engineers and industry experts together to educate, network, and share their expertise with you. Just this year, ASP.NET Core, SQL Server 2016, Visual Studio 2015, Windows 10 and SharePoint 2016 launched. The new release of Windows Server is on the horizon and open source is becoming the norm. The cloud is real and so is cloud scaling. Are you ready? Invest in your companies success – and in your career – at an event where questions are answered, strategies are defined and relationships are built.
  startDate: 2017-10-30
  endDate: 2017-11-2
  link: https://www.spintersection.com/#!/Fall-2017
  where: Las Vegas, NV
  tags: [in-person, conference]
- title: PASS Summit 2017
  desc: |
    PASS Summit connects you with industry experts and global data professionals in a unique learning environment that empowers you with the practical knowledge you need to excel in your career.
  startDate: 2017-10-31
  endDate: 2017-11-3
  link: http://www.pass.org/summit/2017/Home.aspx
  where: Seattle, WA
  tags: [in-person, conference]
- title: DeveloperWeek 2018
  desc: |
    Join 8,000 attendees at one of San Francisco’s largest technology-neutral programming conferences & expos. See the full agenda of talks. Join us for the Expo Block party.
  startDate: 2018-2-03
  endDate: 2018-2-08
  link: http://www.developerweek.com//
  where: San Francisco
  tags: [in-person, conference]
- title: Microsoft Ignite
  desc: |
    Microsoft Ignite gives you five days of hands-on learning, industry insights, and direct access to product experts—all in one place. 
    
    700+ sessions
    Interactive Digital Labs
    Direct access to product experts
    Deep dives and demos
    300+ partners at the expo
    Product roadmaps, vision, and strategies
  startDate: 2018-9-24
  endDate: 2018-9-28
  link: https://ignite.microsoft.com/
  where: Orlando, FL
  tags: [in-person, conference]
